[project]
name = "personalization-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohit Tudu", email = "rohittudu181@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.0",
    "scikit-surprise>=1.1.5",
    "uvicorn>=0.52.1",
]

[project.scripts]
personalization-service = "personalization_service:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
