[project]
name = "auth-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohit Tudu", email = "rohittudu181@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "bcrypt>=5.0.0",
    "fastapi>=0.141.1",
    "passlib>=1.7.4",
    "psycopg>=3.3.4",
    "pydantic-settings>=2.15.0",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.1",
]

[project.scripts]
auth-service = "auth_service:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
