[project]
name = "commerce-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Rohit Tudu", email = "rohittudu181@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "psycopg[binary]>=3.3.4",
    "pydantic-settings>=2.15.0",
    "redis>=8.1.0",
    "sqlalchemy>=2.0.52",
    "stripe>=15.5.0",
    "uvicorn>=0.52.1",
]

[project.scripts]
commerce-service = "commerce_service:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"
